services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pfinance?schema=public
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - pfinance-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pfinance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pfinance-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  pfinance-network:
    driver: bridge 